### ISSUE TITLE
重启失败

### ISSUE THREAD

**Issue by a74731248** [ThomasZN/v2sub#4]
在选择节点之后，重启v2ray服务失败。exit status 5

**Comment by ThomasZN** [comment]
```
使用前需确保 v2ray.service 服务已注册且默认 v2ray 配置文件路径为 /etc/v2ray.json 。
```

这里 exit status 5 应该是服务未正确注册，你可以通过命令 `sudo systemctl restart v2ray.service` 来检查。

**Comment by a74731248** [comment]
> ```
> 使用前需确保 v2ray.service 服务已注册且默认 v2ray 配置文件路径为 /etc/v2ray.json 。
> ```
> 
> 这里 exit status 5 应该是服务未正确注册，你可以通过命令 `sudo systemctl restart v2ray.service` 来检查。

已经好了，是我的v2ray服务启动异常。现在我发现我启动成功了，但是依然ping不同google.com啊，这是为啥

**Comment by ThomasZN** [comment]
`ping` 命令走的是ICMP协议，和TCP协议不在一个网络层，无法直接通过v2ray转发。

如果你想测试代理可用性，可以在命令行开启代理后使用命令 `curl www.google.com` 。

**Comment by ThomasZN** [comment]
重启的问题已解决，issue关闭了哦
